branches: [main]
repositoryUrl: https://github.com/karl-cardenas-coding/waypoint-deployment-pattern.git
plugins:
- "@semantic-release/commit-analyzer"
- "@semantic-release/release-notes-generator"
- "@semantic-release/changelog"
- - "@semantic-release/exec"
- - "@semantic-release/github"
- - "@semantic-release/git"
  - assets:
    - CHANGELOG.md